[package]
name = "endbasic"
version = "0.5.0"
license = "Apache-2.0"
authors = ["Julio Merino <julio@meroh.net>"]
categories = ["development-tools", "parser-implementations"]
keywords = ["basic", "interpreter", "learning", "programming"]
description = "The EndBASIC programming language - CLI"
homepage = "https://github.com/jmmv/endbasic"
repository = "https://github.com/jmmv/endbasic"
readme = "README.md"
edition = "2018"

[[bin]]
name = "endbasic"
required-features = ["endbasic-std/crossterm"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
dirs = "2.0"
endbasic-core = { version = "0.5.0", path = "../core" }
endbasic-std = { version = "0.5.0", path = "../std", default-features = false }
futures-lite = "1.1"
getopts = "0.2"
thiserror = "1.0"
time = { version = "0.2", features = ["std"] }

[dev-dependencies]
regex = "1"
tempfile = "3"
