[package]
name = "endbasic-std"
version = "0.5.1"
license = "Apache-2.0"
authors = ["Julio Merino <julio@meroh.net>"]
categories = ["development-tools", "parser-implementations"]
keywords = ["basic", "interpreter", "learning", "programming"]
description = "The EndBASIC programming language - standard library"
homepage = "https://github.com/jmmv/endbasic"
repository = "https://github.com/jmmv/endbasic"
readme = "README.md"
edition = "2018"

[features]
default = ["crossterm"]

[dependencies]
async-trait = "0.1"
crossterm = { version = "0.18", optional = true }
endbasic-core = { version = "0.5.1", path = "../core" }
futures-lite = "1.1"
time = { version = "0.2", features = ["std"] }

# We don't directly use getrandom but rand does, and we have to customize how
# getrandom is built if we want it to work in a WASM context.
[dependencies.getrandom]
version = "0.2"
features = ["js"]

[dependencies.rand]
version = "0.8"
default-features = false
features = ["small_rng", "std"]

[dev-dependencies]
filetime = "0.2"
tempfile = "3"
