[package]
name = "endbasic-web"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Julio Merino <julio@meroh.net>"]
categories = ["development-tools", "parser-implementations"]
keywords = ["basic", "interpreter", "learning", "programming"]
description = "The EndBASIC programming language - web interface"
homepage = "https://github.com/jmmv/endbasic"
repository = "https://github.com/jmmv/endbasic"
readme = "README.md"
edition = "2018"
build = "build.rs"
publish = false

[badges]
travis-ci = { repository = "jmmv/endbasic", branch = "master" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
async-trait = "0.1"
console_error_panic_hook = { version = "0.1.6", optional = true }
endbasic-core = { version = "0.2.0", path = "../core" }
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.2", features = ["serde", "std"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
xterm-js-rs = "0.1.1"

[dependencies.web-sys]
version = "0.3"
features = [
    "Storage",
    "Window",
]

[build-dependencies]
vergen = "3"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.wasm-pack.profile.release]
# Workaround for https://github.com/rustwasm/wasm-pack/issues/886, which
# started happening with wasm-bindgen 0.2.66.
wasm-opt = ["-O", "--enable-mutable-globals"]
